### ISSUE TITLE
ASAN crash in libtest with --help command line argument

### ISSUE THREAD

**Issue by justinclift** [FLIF-hub/FLIF#235]
Tried running `libtest`, using "--help" as the only command line argument.  Immediate ASAN crash:

```
$ LD_PRELOAD=libasan.so.2 ./libtest --help
=================================================================
==26982==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000c044 at pc 0x7f1c1d9d7f93 bp 0x7ffda50329b0 sp 0x7ffda50329a0
READ of size 4 at 0x60200000c044 thread T0
    #0 0x7f1c1d9d7f92 in Plane<unsigned char>::get_fast(unsigned int, unsigned int) const /home/jc/git_repos/FLIF/src/maniac/../image/image.hpp:258
    #1 0x7f1c1d9d7f92 in void flif_decode_plane_zoomlevel_vertical<FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>, Plane<unsigned char>, Plane<unsigned char>, 0, ColorRangesBounds>(Plane<unsigned char>&, FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>&, std::vector<Image, std::allocator<Image> >&, ColorRangesBounds const*, Plane<unsigned char> const&, Plane<unsigned char> const&, std::vector<int, std::allocator<int> >&, int, int, unsigned int, bool, bool) /home/jc/git_repos/FLIF/src/flif-dec.cpp:383
    #2 0x7f1c1d9d882d in vertical_plane_decoder<FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>, Plane<unsigned char>, 0, ColorRangesBounds>::visit(Plane<unsigned char>&) /home/jc/git_repos/FLIF/src/flif-dec.cpp:450
    #3 0x7f1c1d348b01 in bool flif_decode_FLIF2_inner_vertical<FileIO, RacInput24<FileIO>, FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>, Plane<unsigned char>, 0, ColorRangesBounds>(FileIO&, RacInput24<FileIO>&, std::vector<FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>, std::allocator<FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10> > >&, std::vector<Image, std::allocator<Image> >&, ColorRangesBounds const*, int, int, int, int, int, int) /home/jc/git_repos/FLIF/src/flif-dec.cpp:529
    #4 0x7f1c1d35b4de in bool flif_decode_FLIF2_inner_vertical_p<FileIO, RacInput24<FileIO>, FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>, Plane<unsigned char>, ColorRangesBounds>(int, FileIO&, RacInput24<FileIO>&, std::vector<FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>, std::allocator<FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10> > >&, std::vector<Image, std::allocator<Image> >&, ColorRangesBounds const*, int, int, int, int, int, int) /home/jc/git_repos/FLIF/src/flif-dec.cpp:552
    #5 0x7f1c1d35b4de in bool flif_decode_FLIF2_inner<FileIO, RacInput24<FileIO>, FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>, ColorRangesBounds>(FileIO&, RacInput24<FileIO>&, std::vector<FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10>, std::allocator<FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10> > >&, std::vector<Image, std::allocator<Image> >&, ColorRangesBounds const*, int, int, int, int, std::vector<Transform<FileIO>*, std::allocator<Transform<FileIO>*> >&, unsigned int (*)(int, long), std::vector<Image, std::allocator<Image> >&) /home/jc/git_repos/FLIF/src/flif-dec.cpp:600
    #6 0x7f1c1d3852fb in bool flif_decode_FLIF2_pass<FileIO, RacInput24<FileIO>, FinalPropertySymbolCoder<SimpleBitChance, RacInput24<FileIO>, 10> >(FileIO&, RacInput24<FileIO>&, std::vector<Image, std::allocator<Image> >&, ColorRanges const*, std::vector<Tree, std::allocator<Tree> >&, int, int, int, int, std::vector<Transform<FileIO>*, std::allocator<Transform<FileIO>*> >&, unsigned int (*)(int, long), std::vector<Image, std::allocator<Image> >&, int, int) /home/jc/git_repos/FLIF/src/flif-dec.cpp:656
    #7 0x7f1c1d4ed1c3 in bool flif_decode_main<10, FileIO>(RacInput24<FileIO>&, FileIO&, std::vector<Image, std::allocator<Image> >&, ColorRanges const*, std::vector<Transform<FileIO>*, std::allocator<Transform<FileIO>*> >&, int, int, unsigned int (*)(int, long), std::vector<Image, std::allocator<Image> >&, int, int, int) /home/jc/git_repos/FLIF/src/flif-dec.cpp:693
    #8 0x7f1c1d4f5084 in bool flif_decode<FileIO>(FileIO&, std::vector<Image, std::allocator<Image> >&, int, int, unsigned int (*)(int, long), int, std::vector<Image, std::allocator<Image> >&, int, int, int) /home/jc/git_repos/FLIF/src/flif-dec.cpp:947
    #9 0x7f1c1dbe50dc in FLIF_DECODER::decode_file(char const*) /home/jc/git_repos/FLIF/src/library/flif-interface_dec.cpp:44
    #10 0x7f1c1dbe7400 in flif_decoder_decode_file /home/jc/git_repos/FLIF/src/library/flif-interface_dec.cpp:192
    #11 0x40182c in main /home/jc/git_repos/FLIF/tools/test.c:214
    #12 0x7f1c1c9ee57f in __libc_start_main (/lib64/libc.so.6+0x2057f)
    #13 0x401e18 in _start (/home/jc/git_repos/FLIF/src/libtest+0x401e18)

0x60200000c044 is located 4 bytes to the right of 16-byte region [0x60200000c030,0x60200000c040)
allocated by thread T0 here:
    #0 0x7f1c1df27872 in operator new(unsigned long) (/lib64/libasan.so.2+0x99872)
    #1 0x7f1c1d2b5d46 in std::unique_ptr<ConstantPlane, std::default_delete<ConstantPlane> > make_unique<ConstantPlane, int const&>(int const&) /home/jc/git_repos/FLIF/src/maniac/../image/image.hpp:154
    #2 0x7f1c1d2b5d46 in Image::make_constant_plane(int, int) /home/jc/git_repos/FLIF/src/maniac/../image/image.hpp:667

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/jc/git_repos/FLIF/src/maniac/../image/image.hpp:258 Plane<unsigned char>::get_fast(unsigned int, unsigned int) const
Shadow bytes around the buggy address:
  0x0c047fff97b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fd fd
  0x0c047fff97c0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fff97d0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fd
  0x0c047fff97e0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa 00 00
  0x0c047fff97f0: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa fd fd
=>0x0c047fff9800: fa fa 00 00 fa fa 00 00[fa]fa 00 00 fa fa fd fd
  0x0c047fff9810: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fd
  0x0c047fff9820: fa fa fd fa fa fa fd fd fa fa 00 00 fa fa fd fa
  0x0c047fff9830: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fa
  0x0c047fff9840: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fd
  0x0c047fff9850: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==26982==ABORTING
```

`libtest` isn't exactly a production library, but this might still be useful to follow up anyway.  Barfing on "--help" is probably not what's intended. :wink:

**Comment by jonsneyers** [comment]
Did you compile with clang? Might be fixed now. It will use "--help" as a filename though, so that might cause trouble if your OS does not allow such a filename.

**Comment by justinclift** [comment]
The above was with gcc on Fedora 23.  Haven't gotten around to trying clang on Fedora yet, even though it's a good idea.  Likely next few days. :grinning:

I'll give your new code a shot in a minute, and see if the bug was affecting gcc as well somehow...

**Comment by justinclift** [comment]
Btw, are segfaults when processing malformed data of interest?

**Comment by justinclift** [comment]
Good news with this bug too.  Seems fixed now. :smile:

```bash
$ LD_PRELOAD=libasan.so.2 ./libtest --help
interface test has succeeded.
```

**Comment by jonsneyers** [comment]
OK, nice.

**Comment by jonsneyers** [comment]
Thanks for the report!
