### ISSUE TITLE
heap out of bounds read in TransformPaletteC<FileIO>::invData

### ISSUE THREAD

**Issue by hannob** [FLIF-hub/FLIF#277]
The attached file (zip'ed) is a malformed flif file that will cause an out of bounds heap read. This was discovered with the help of american fuzzy lop and address sanitizer.

To see this issue you need to compile flif with address sanitizer enabled (-fsanitize=address in CFLAGS).

Address sanitizer error message:
```
==12583==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000ee50 at pc 0x000000566028 bp 0x7fff13ad5b00 sp 0x7fff13ad5af8
READ of size 4 at 0x60300000ee50 thread T0
    #0 0x566027 in TransformPaletteC<FileIO>::invData(std::vector<Image, std::allocator<Image> >&) const /f/flif/FLIF/src/transform/palette_C.hpp:79:34
    #1 0x6d8983 in bool flif_decode<FileIO>(FileIO&, std::vector<Image, std::allocator<Image> >&, int, int, unsigned int (*)(int, long), int, std::vector<Image, std::allocator<Image> >&, int, int, int, bool) /f/flif/FLIF/src/flif-dec.cpp:1064:9
    #2 0xb4d5a8 in bool flif_decode<FileIO>(FileIO&, std::vector<Image, std::allocator<Image> >&, int, int, int, int, int, bool) /f/flif/FLIF/src/./flif-dec.hpp:7:138
    #3 0xb4d5a8 in decode_flif(char**, std::vector<Image, std::allocator<Image> >&, int, int, int, int, int, bool) /f/flif/FLIF/src/flif.cpp:310
    #4 0xb4d5a8 in handle_decode(int, char**, std::vector<Image, std::allocator<Image> >&, int, int, int, int, int, bool) /f/flif/FLIF/src/flif.cpp:327
    #5 0xb51d27 in main /f/flif/FLIF/src/flif.cpp:624:16
    #6 0x7f448eac178f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.23-r2/work/glibc-2.23/csu/../csu/libc-start.c:289
    #7 0x41b2f8 in _start (/mnt/ram/flif/flif+0x41b2f8)

0x60300000ee50 is located 0 bytes to the right of 32-byte region [0x60300000ee30,0x60300000ee50)
allocated by thread T0 here:
    #0 0x4f3e30 in operator new(unsigned long) (/mnt/ram/flif/flif+0x4f3e30)
    #1 0x537ab8 in __gnu_cxx::new_allocator<int>::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/ext/new_allocator.h:104:27
    #2 0x537ab8 in std::allocator_traits<std::allocator<int> >::allocate(std::allocator<int>&, unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/alloc_traits.h:357
    #3 0x537ab8 in std::_Vector_base<int, std::allocator<int> >::_M_allocate(unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:170
    #4 0x537ab8 in void std::vector<int, std::allocator<int> >::_M_emplace_back_aux<int>(int&&) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/vector.tcc:412
    #5 0x537ab8 in void std::vector<int, std::allocator<int> >::emplace_back<int>(int&&) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/vector.tcc:101
    #6 0x537ab8 in std::vector<int, std::allocator<int> >::push_back(int&&) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:932
    #7 0xb7265f in _fini (/mnt/ram/flif/flif+0xb7265f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /f/flif/FLIF/src/transform/palette_C.hpp:79:34 in TransformPaletteC<FileIO>::invData(std::vector<Image, std::allocator<Image> >&) const
Shadow bytes around the buggy address:
  0x0c067fff9d70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9d80: fa fa fa fa fa fa fa fa fa fa fd fd fd fd fa fa
  0x0c067fff9d90: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c067fff9da0: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
  0x0c067fff9db0: fd fd fa fa fd fd fd fd fa fa 00 00 00 00 fa fa
=>0x0c067fff9dc0: 00 00 00 00 fa fa 00 00 00 00[fa]fa 00 00 00 00
  0x0c067fff9dd0: fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa fd fd
  0x0c067fff9de0: fd fa fa fa 00 00 00 00 fa fa fd fd fd fd fa fa
  0x0c067fff9df0: 00 00 00 00 fa fa 00 00 00 07 fa fa 00 00 00 06
  0x0c067fff9e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9e10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==12583==ABORTING
[flif-heap-oob-TransformPaletteC.zip](https://github.com/FLIF-hub/FLIF/files/366660/flif-heap-oob-TransformPaletteC.zip)

**Comment by jonsneyers** [comment]
Thanks for the report. I'm trying to reproduce on the current version (the bitstream changed so the example no longer works).

The problem is probably that a malformed file somehow manages to refer to a color which is out of the range for ChannelCompact. We could systematically check for this when decompacting the channels, but that would make decoding slightly slower for all files, so I'd rather understand how it manages to decode an out-of-range value in the first place, because that could indicate a missed compression opportunity.

**Comment by hannob** [comment]
Took just some seconds to refind the bug in the latest git code. (You should probably use some kind of simple fuzzing in the development/testing process if you're developing an image parser - these things are very prone to typical fuzzing-bugs.)

[flif-oob-TransformPaletteC-FileIO-invData.zip](https://github.com/FLIF-hub/FLIF/files/441115/flif-oob-TransformPaletteC-FileIO-invData.zip)

**Comment by jonsneyers** [comment]
Thanks! I did some afl-fuzzing and also refound (a few instances of) this bug, and some other bugs as well. It's a pretty useful tool, this afl fuzzer...
